<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataSourceSeeder extends Seeder
{
    public function run(): void
    {
        $sources = [
            // ── FREE TIER — Pakistan ──────────────────────────────────────────
            [
                'name'                     => 'PPRA Federal',
                'slug'                     => 'ppra_federal',
                'country_code'             => 'PK',
                'tier'                     => 'free',
                'url'                      => 'https://epms.ppra.gov.pk/public/tenders/active-tenders',
                'scraper_class'            => 'App\Modules\Scraper\Services\Sources\Pakistan\PpraFederalScraper',
                'scraper_type'             => 'html',
                'is_active'                => true,
                'requires_proxy'           => false,
                'scrape_frequency_hours'   => 6,
                'rate_limit_delay_seconds' => 2,
                'notes'                    => 'Verified. Clean HTML, no login, no CAPTCHA.',
            ],
            [
                'name'                     => 'SPPRA (Sindh)',
                'slug'                     => 'sppra',
                'country_code'             => 'PK',
                'tier'                     => 'free',
                'url'                      => 'https://pprasindh.gov.pk/tendersdepartment.php',
                'scraper_class'            => 'App\Modules\Scraper\Services\Sources\Pakistan\SppraScraper',
                'scraper_type'             => 'html',
                'is_active'                => true,
                'requires_proxy'           => false,
                'scrape_frequency_hours'   => 6,
                'rate_limit_delay_seconds' => 2,
                'notes'                    => null,
            ],
            [
                'name'                     => 'KPPRA (KPK)',
                'slug'                     => 'kppra',
                'country_code'             => 'PK',
                'tier'                     => 'free',
                'url'                      => 'http://www.kppra.gov.pk/kppra/activetenders.php',
                'scraper_class'            => 'App\Modules\Scraper\Services\Sources\Pakistan\KppraScraper',
                'scraper_type'             => 'html',
                'is_active'                => true,
                'requires_proxy'           => false,
                'scrape_frequency_hours'   => 6,
                'rate_limit_delay_seconds' => 2,
                'notes'                    => null,
            ],
            [
                'name'                     => 'BPPRA (Balochistan)',
                'slug'                     => 'bppra',
                'country_code'             => 'PK',
                'tier'                     => 'free',
                'url'                      => 'https://bppthree.vdc.services/tenderssearch/',
                'scraper_class'            => 'App\Modules\Scraper\Services\Sources\Pakistan\BppraScraper',
                'scraper_type'             => 'html',
                'is_active'                => true,
                'requires_proxy'           => false,
                'scrape_frequency_hours'   => 8,
                'rate_limit_delay_seconds' => 3,
                'notes'                    => null,
            ],

            // ── STARTER $29/mo — UK (free official APIs) ─────────────────────
            [
                'name'                     => 'UK Find a Tender (FTS)',
                'slug'                     => 'uk_fts',
                'country_code'             => 'GB',
                'tier'                     => 'starter',
                'url'                      => 'https://www.find-tender.service.gov.uk/api/1.0/ocdsReleasePackages',
                'scraper_class'            => 'App\Modules\Scraper\Services\Sources\UK\UkFindTenderScraper',
                'scraper_type'             => 'api',
                'is_active'                => true,
                'requires_proxy'           => false,
                'scrape_frequency_hours'   => 6,
                'rate_limit_delay_seconds' => 1,
                'notes'                    => 'Free OCDS API. Open Government Licence. 1000+/week, contracts >£139k.',
            ],
            [
                'name'                     => 'UK Contracts Finder',
                'slug'                     => 'uk_cf',
                'country_code'             => 'GB',
                'tier'                     => 'starter',
                'url'                      => 'https://www.contractsfinder.service.gov.uk/Published/Notices/PublicSearch/Search',
                'scraper_class'            => 'App\Modules\Scraper\Services\Sources\UK\UkContractsFinderScraper',
                'scraper_type'             => 'api',
                'is_active'                => true,
                'requires_proxy'           => false,
                'scrape_frequency_hours'   => 6,
                'rate_limit_delay_seconds' => 1,
                'notes'                    => 'Free JSON API. Covers lower-value contracts (>£12k) that FTS misses. Complements uk_fts.',
            ],

            // ── PROFESSIONAL $49/mo — Global (free APIs + public HTML) ────────
            [
                'name'                     => 'World Bank',
                'slug'                     => 'world_bank',
                'country_code'             => '*',
                'tier'                     => 'professional',
                'url'                      => 'http://search.worldbank.org/api/procnotices',
                'scraper_class'            => 'App\Modules\Scraper\Services\Sources\International\WorldBankScraper',
                'scraper_type'             => 'api',
                'is_active'                => true,
                'requires_proxy'           => false,
                'scrape_frequency_hours'   => 4,
                'rate_limit_delay_seconds' => 1,
                'notes'                    => 'Free JSON API, CC licensed. $1M-$100M+ contracts. 500+ active/month.',
            ],
            [
                'name'                     => 'USA SAM.gov',
                'slug'                     => 'sam_gov',
                'country_code'             => 'US',
                'tier'                     => 'professional',
                'url'                      => 'https://api.sam.gov/prod/opportunities/v2/search',
                'scraper_class'            => 'App\Modules\Scraper\Services\Sources\USA\SamGovScraper',
                'scraper_type'             => 'api',
                'is_active'                => true,
                'requires_proxy'           => false,
                'scrape_frequency_hours'   => 6,
                'rate_limit_delay_seconds' => 1,
                'notes'                    => 'Free API key from api.sam.gov. Requires SAM_GOV_API_KEY in .env.',
            ],
            [
                'name'                     => 'UNGM (United Nations)',
                'slug'                     => 'ungm',
                'country_code'             => '*',
                'tier'                     => 'professional',
                'url'                      => 'https://www.ungm.org/Public/Notice',
                'scraper_class'            => 'App\Modules\Scraper\Services\Sources\International\UngmScraper',
                'scraper_type'             => 'html',
                'is_active'                => true,
                'requires_proxy'           => false,
                'scrape_frequency_hours'   => 8,
                'rate_limit_delay_seconds' => 3,
                'notes'                    => 'All UN agencies. Public HTML, no login. 3s delay required.',
            ],
            [
                'name'                     => 'ADB (Asian Development Bank)',
                'slug'                     => 'adb',
                'country_code'             => '*',
                'tier'                     => 'professional',
                'url'                      => 'https://www.adb.org/projects/tenders/active',
                'scraper_class'            => 'App\Modules\Scraper\Services\Sources\International\AdbScraper',
                'scraper_type'             => 'html',
                'is_active'                => true,
                'requires_proxy'           => false,
                'scrape_frequency_hours'   => 8,
                'rate_limit_delay_seconds' => 3,
                'notes'                    => 'Heavy Pakistan/Asia focus. Public HTML.',
            ],
            [
                'name'                     => 'AfDB (African Development Bank)',
                'slug'                     => 'afdb',
                'country_code'             => '*',
                'tier'                     => 'professional',
                'url'                      => 'https://www.afdb.org/en/rss/procurement-notices',
                'scraper_class'            => 'App\Modules\Scraper\Services\Sources\International\AfdbScraper',
                'scraper_type'             => 'rss',
                'is_active'                => true,
                'requires_proxy'           => false,
                'scrape_frequency_hours'   => 12,
                'rate_limit_delay_seconds' => 2,
                'notes'                    => 'RSS feed. ~100/month. Africa focus.',
            ],

            // ── DISABLED — UAE/Saudi (JS-heavy, login walls) ──────────────────
            [
                'name'                     => 'ADGPG (Abu Dhabi)',
                'slug'                     => 'adgpg',
                'country_code'             => 'AE',
                'tier'                     => 'starter',
                'url'                      => 'https://www.adgpg.gov.ae/en/For-Suppliers/Public-Tenders',
                'scraper_class'            => 'App\Modules\Scraper\Services\Sources\UAE\AdgpgScraper',
                'scraper_type'             => 'headless',
                'is_active'                => false,
                'requires_proxy'           => false,
                'scrape_frequency_hours'   => 6,
                'rate_limit_delay_seconds' => 3,
                'notes'                    => 'DISABLED: JS SPA, TAMM internal API. Phase 2.',
            ],
            [
                'name'                     => 'Dubai Municipality',
                'slug'                     => 'dubai_esupply',
                'country_code'             => 'AE',
                'tier'                     => 'starter',
                'url'                      => 'https://www.dm.gov.ae/municipality-business/tenders-biddings/',
                'scraper_class'            => 'App\Modules\Scraper\Services\Sources\UAE\DubaiEsupplyScraper',
                'scraper_type'             => 'html',
                'is_active'                => false,
                'requires_proxy'           => false,
                'scrape_frequency_hours'   => 6,
                'rate_limit_delay_seconds' => 3,
                'notes'                    => 'DISABLED: No active tenders on page currently. Phase 2.',
            ],
            [
                'name'                     => 'RTA Dubai',
                'slug'                     => 'dubai_rta',
                'country_code'             => 'AE',
                'tier'                     => 'starter',
                'url'                      => 'https://www.rta.ae/wps/portal/rta/ae/about-rta/procurement/open-tenders',
                'scraper_class'            => 'App\Modules\Scraper\Services\Sources\UAE\DubaiRtaScraper',
                'scraper_type'             => 'headless',
                'is_active'                => false,
                'requires_proxy'           => false,
                'scrape_frequency_hours'   => 6,
                'rate_limit_delay_seconds' => 3,
                'notes'                    => 'DISABLED: JS SPA. Phase 2.',
            ],
            [
                'name'                     => 'DEWA',
                'slug'                     => 'dewa',
                'country_code'             => 'AE',
                'tier'                     => 'starter',
                'url'                      => 'https://www.dewa.gov.ae/en/about-dewa/procurement/current-tenders',
                'scraper_class'            => 'App\Modules\Scraper\Services\Sources\UAE\DewaScraper',
                'scraper_type'             => 'headless',
                'is_active'                => false,
                'requires_proxy'           => false,
                'scrape_frequency_hours'   => 6,
                'rate_limit_delay_seconds' => 3,
                'notes'                    => 'DISABLED: Akamai WAF (403). Phase 2.',
            ],
            [
                'name'                     => 'Etimad (Saudi Arabia)',
                'slug'                     => 'etimad',
                'country_code'             => 'SA',
                'tier'                     => 'professional',
                'url'                      => 'https://tenders.etimad.sa/Tender/AllTendersForVistor',
                'scraper_class'            => 'App\Modules\Scraper\Services\Sources\Saudi\EtimadScraper',
                'scraper_type'             => 'html',
                'is_active'                => false,
                'requires_proxy'           => false,
                'scrape_frequency_hours'   => 6,
                'rate_limit_delay_seconds' => 3,
                'notes'                    => 'DISABLED: JS-rendered. Use TendersAlerts API in Phase 2 (>$2k MRR).',
            ],
        ];

        foreach ($sources as $source) {
            $existing = DB::table('data_sources')->where('slug', $source['slug'])->first();

            DB::table('data_sources')->updateOrInsert(
                ['slug' => $source['slug']],
                array_merge($source, [
                    'total_tenders_scraped' => $existing->total_tenders_scraped ?? 0,
                    'success_rate_7d'       => $existing->success_rate_7d ?? 0,
                    'created_at'            => $existing->created_at ?? now(),
                    'updated_at'            => now(),
                ])
            );
        }

        $active = collect($sources)->where('is_active', true)->count();
        $this->command->info("DataSourceSeeder: " . count($sources) . " sources seeded, {$active} active.");
    }
}
